caves:
  ins:
    enabled: true
    chance: 0.0025
  hungering-darkness: true
  ambient-sounds:
    chance: 0.25
  temperature:
    chance: 0.15
  aging:
    chance: 0.5
    change-chance: 0.25
generator:
  structures: true
  chance: 0.5
  skulls: true
  easter-egg: true
mobs:
  enabled: true
  y-min: 0
  y-max: 64
  chance: 1