caves:
  ins:
    chance: 0.0025
  hungering-darkness: true
  ambient-sounds:
    chance: 0.25
  temperature:
    chance: 0.15
  aging:
    chance: 0.5
    change-chance: 0.25
generator:
  worlds:
    - world
  chest-items:
    - sugar
    - torch
    - dirt
  try-chance: 0.5
  traps: true
  pillars: true
  boulders: true
  buildings: true
  skulls: true
  easter-egg: true
mobs:
  worlds:
    - world
  enabled: true
  y-min: 0
  y-max: 64
  try-chance: 1