name: DangerousCaves
version: ${version}-${cfgVersion}
main: com.github.evillootlye.caves.DangerousCaves
api-version: 1.13
authors: [Evil-Lootlye, imDaniX]
description: ${description}
commands:
  dangerouscaves:
    aliases: [dcaves, dc]
    usage: "/<command> [info|summon|tick|reload]"
    permission: dangerous.caves.command