name: DangerousCaves
version: ${project.version}
main: com.github.evillootlye.caves.DangerousCaves
api-version: 1.13
authors: [DaddyLootly]
description: Adds and improves mechanics in caves.
commands:
  dangerouscaves:
    aliases: [dcaves, dc]
    usage: "/<command> [info|summon|reload]"
    permission: dangerous.caves.command