name: DangerousCaves
version: ${version}.${subVersion}-${cfgVersion}
main: me.imdanix.caves.DangerousCaves
api-version: "1.13"
authors: [imDaniX, Evil-Lootlye]
description: ${description}
commands:
  dangerouscaves:
    aliases: [dcaves, dc]
    usage: "/<command> [info|summon|tick|reload]"
    permission: dangerous.caves.command